name:                haskell-style-checker
version:             2.0.0.0
github:              "Epitech/haskell-style-checker"
license:             BSD3
author:              ["Arthur Soulié", "Marc Planard"]
maintainer:          "arthur2.soulie@epitech.eu"

description:         Please see the README on GitHub at <https://github.com/Epitech/haskell-style-checker#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.16 && < 0.17
- mtl >= 2.2
- directory >= 1.3
- filepath >= 1.4
- haskell-src-exts >= 1.23

library:
  source-dirs: src
  ghc-options:
  - -O3
  - -Wall

executables:
  haskell-style-checker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    - -Wall
    dependencies:
    - haskell-style-checker

tests:
  integration-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-style-checker
    - hspec >= 2.7
