name:                lambdananas
version:             2.3.1.0
github:              "Epitech/lambdananas"
license:             BSD3
author:              ["Arthur Soulié", "Marc Planard"]
maintainer:          "arthur2.soulie@epitech.eu"
description:         Please see the README on GitHub at <https://github.com/Epitech/lambdananas#readme>
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.16 && < 0.17
- mtl >= 2.2
- directory >= 1.3
- filepath >= 1.4
- haskell-src-exts >= 1.23
- text >= 1.2 && < 2
- regex-tdfa >= 1.3 && < 2

library:
  source-dirs:
  - src
  - src/rules
  ghc-options:
  - -O3
  - -Wall

executables:
  lambdananas-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O3
    - -Wall
    dependencies:
    - lambdananas

tests:
  integration-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambdananas
    - hspec >= 2.7
