on: [push]
name: Lambdananas Tests
jobs:
  lambdananas:
    name: Unit Tests
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '8.8.4'
          enable-stack: true
          stack-version: 'latest'
      - name: install deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install libgmp-dev -qq
      - name: stack test
        run: stack --system-ghc test
