name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack
    - name: Build
      run: stack build --test --no-run-tests

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack
    - name: Run unit tests
      run: echo "not implemented yet"

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: [unit, build]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack
    - name: Run integration tests
      run: stack test haskell-style-checker:integration-tests

  system:
    name: System tests
    runs-on: ubuntu-latest
    needs: [unit, integration, build]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack
    - name: Run system tests
      run: shelltest -a -d -p test/system/

  artifacts:
    name: Upload artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack
    - name: Building
      run: stack build
    - name: Install to current directory
      run: cp $(stack path --local-install-root)/bin/haskell-style-checker-exe hsc
    - name: Compressing and stripping binary
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        files: |
          hsc
        args: --best
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: hsc
        path: hsc
