name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: 8.8.3
        stack-version: 2.7.5
        enable-stack: true
    - run: stack build --test
