name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack
    - name: Build
      run: stack build

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: stack test haskell-style-checker:unit-tests

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: [unit, build]
    steps:
    - uses: actions/checkout@v2
    - name: Run integration tests
      run: stack test haskell-style-checker:integration-tests

  system:
    name: System tests
    runs-on: ubuntu-latest
    needs: [unit, integration, build]
    steps:
    - uses: actions/checkout@v2
    - name: Run system tests
      run: stack test haskell-style-checker:integration-tests

  artifacts:
    name: Upload artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: stack build
    - uses: gacts/upx@master
      with:
        file: 'hsc'
        upx_args: '--best'
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: hsc
        path: hsc

